### ISSUE TITLE
Problem cloning in windows

### ISSUE THREAD

**Issue by MikeRaben** [emil10001/ActionBarCompatExample#1]
Received errors trying to clone into Android Studio on Windows 7, fixed by deleting the local.properties file. The link below gives a good list of files to include in gitignore, might help others cloning your repos.

https://github.com/github/gitignore/blob/master/Android.gitignore

**Comment by emil10001** [comment]
Darn, my laziness finally caught up with me. =) 

Thanks for the tip, I'll go through and update my projects later today with this.

**Comment by emil10001** [comment]
Ok, up to date. Looks like that was the only file that I didn't catch in the original commits. Thanks again for pointing out the issue!
